# Generated by Django 6.0.6 on 2026-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_technology_options_alter_technology_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repository_host",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
